# Generated by Django 6.0.8 on 2026-09-12 11:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrepPilot', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assistant Conversation',
                'verbose_name_plural': 'Assistant Conversations',
                'db_table': 'assistant_conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyResourceVault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('pdf', 'PDF upload'), ('link', 'Web link')], default='link', max_length=10)),
                ('link_url', models.URLField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='vault/%Y/%m/')),
                ('subject_name', models.CharField(blank=True, max_length=100)),
                ('topic_name', models.CharField(blank=True, max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_items', to=settings.AUTH_USER_MODEL)),
                ('related_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_items', to='PrepPilot.topic')),
            ],
            options={
                'verbose_name': 'Study Resource Vault Item',
                'verbose_name_plural': 'Study Resource Vault Items',
                'db_table': 'study_resource_vault',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'is_published'], name='study_resou_owner_i_c092dc_idx'), models.Index(fields=['is_published', 'created_at'], name='study_resou_is_publ_e859af_idx')],
            },
        ),
    ]
